#!/usr/bin/env node
/**
 * sync.js — Fetch the SkyBridge token list from the API and regenerate:
 *   - tokenlist.json  (Uniswap Token List format)
 *   - token-list.md   (human-readable markdown table)
 *
 * Usage:
 *   SKYBRIDGE_API_URL=https://api.skybridge.dev node sync.js
 *
 * Defaults to http://localhost:5001 for local development.
 */

const https = require('https');
const http = require('http');
const fs = require('fs');
const path = require('path');

const API_URL = process.env.SKYBRIDGE_API_URL ?? 'http://localhost:5001';
const ENDPOINT = `${API_URL}/api/v2/token-list`;

// Human-readable chain names for the markdown table header
const CHAIN_NAMES = {
  1: 'Ethereum',
  11155111: 'Sepolia',
  8453: 'Base',
  84532: 'Base Sepolia',
  10: 'Optimism',
  11155420: 'OP Sepolia',
  7777777: 'Zora',
  999999999: 'Zora Sepolia',
  34443: 'Mode',
  919: 'Mode Testnet',
  130: 'Unichain',
  1301: 'Unichain Sepolia',
  480: 'Worldchain',
  4801: 'Worldchain Sepolia',
  1868: 'Soneium',
  1946: 'Soneium Minato',
  57073: 'Ink',
  763373: 'Ink Sepolia',
};

function fetchJSON(url) {
  return new Promise((resolve, reject) => {
    const client = url.startsWith('https') ? https : http;
    client.get(url, (res) => {
      let data = '';
      res.on('data', (chunk) => { data += chunk; });
      res.on('end', () => {
        if (res.statusCode !== 200) {
          return reject(new Error(`HTTP ${res.statusCode} from ${url}`));
        }
        try {
          resolve(JSON.parse(data));
        } catch (e) {
          reject(new Error(`Failed to parse JSON from ${url}: ${e.message}`));
        }
      });
    }).on('error', reject);
  });
}

async function main() {
  console.log(`Fetching token list from ${ENDPOINT}...`);
  const list = await fetchJSON(ENDPOINT);

  if (!list.tokens || !Array.isArray(list.tokens)) {
    throw new Error('Unexpected response shape — missing tokens array');
  }

  console.log(`  Received ${list.tokens.length} tokens`);

  // ── tokenlist.json ──────────────────────────────────────────────────────────
  const jsonPath = path.join(__dirname, 'tokenlist.json');
  fs.writeFileSync(jsonPath, JSON.stringify(list, null, 2) + '\n');
  console.log(`  Written: tokenlist.json`);

  // ── token-list.md ───────────────────────────────────────────────────────────
  // Collect all destination chain IDs present in this list
  const destChainIds = new Set();
  for (const token of list.tokens) {
    for (const chainId of Object.keys(token.extensions?.bridgeInfo ?? {})) {
      destChainIds.add(Number(chainId));
    }
  }
  const sortedChainIds = [...destChainIds].sort((a, b) => a - b);

  // Build header
  const chainHeaders = sortedChainIds
    .map(id => CHAIN_NAMES[id] ?? `Chain ${id}`)
    .join(' | ');
  const headerDivider = sortedChainIds.map(() => '---').join(' | ');

  const header = [
    `# SkyBridge Token List`,
    ``,
    `> Auto-generated by \`sync.js\`. Do not edit manually.`,
    `> Source: \`GET /api/v2/token-list\``,
    ``,
    `| Name | Symbol | Decimals | L1 Address | ${chainHeaders} |`,
    `|---|---|---|---|${headerDivider}|`,
  ].join('\n');

  // Build rows
  const rows = list.tokens.map((token) => {
    const bridgeInfo = token.extensions?.bridgeInfo ?? {};
    const l2Cells = sortedChainIds
      .map(id => bridgeInfo[String(id)]?.tokenAddress ?? '—')
      .join(' | ');
    return `| ${token.name} | ${token.symbol} | ${token.decimals} | ${token.address} | ${l2Cells} |`;
  });

  const md = header + '\n' + rows.join('\n') + '\n';
  const mdPath = path.join(__dirname, 'token-list.md');
  fs.writeFileSync(mdPath, md);
  console.log(`  Written: token-list.md`);

  console.log(`Done.`);
}

main().catch((e) => {
  console.error('sync failed:', e.message);
  process.exit(1);
});
